### ISSUE TITLE
Check Tukey numbers

### ISSUE THREAD

**Issue by SmithEcophysLab** [SmithEcophysLab/mdi_pitchpine#1]
there seems to be some disparity in the linear model and Tukey values shown on the plots. These need to be checked.

**Comment by rmcnellis** [comment]
There was an issue with the results of the Tukey's test sorting the sites in a different order than in the dataframe. I just fixed it!

**Comment by SmithEcophysLab** [comment]
Risa, when you go through the manuscript, please carefully check the wording for these comparisons in the Results and Discussion. I'm sure that I mixed them up
