### ISSUE TITLE
stand density plot needs y-axis label change

### ISSUE THREAD

**Issue by SmithEcophysLab** [SmithEcophysLab/mdi_pitchpine#2]
this should be distance between neighbors

**Comment by SmithEcophysLab** [comment]
Now I'm actually confused about this. We need check with Jeff as it is not consistent in the ms

**Comment by rmcnellis** [comment]
Changed the axis title to "Distance Between Neighbors" as I believe that's more accurate. I think that was my fault for misunderstanding that mean distance and stand density are actually inverse!

**Comment by SmithEcophysLab** [comment]
Risa, when you go through the manuscript, please check the wording on this in the Results and Discussion (including in my edits)
